#!/usr/bin/env bash
# Redraw every figure from what out/ already holds. Nothing is recomputed, so
# this is what to run after a change to a figure script rather than run_all.sh,
# which retraces the conduits and takes hours.
#
#   ./refigure.sh              paper figures, supplement, and the checks
#   ./refigure.sh GLADM35      only the supplement sections for one model
#
# Every script writes straight into Paper_plumes/figures. The earlier version
# wrote into plume_pipeline/figures and copied across, which left two
# directories holding same-named files of different ages; the build read the
# older set once.
set -euo pipefail
cd "$(dirname "$0")"

eval "$(grep -E '^(ROOT|TOMO|PAPER_MODEL)=' run_all.sh)"
eval "$(sed -n '/^MODELS=(/,/^)/p' run_all.sh)"
ONLY="${1:-}"
FIGDIR=../figures
mkdir -p "$FIGDIR"

model_file () {
    for m in "${MODELS[@]}"; do
        IFS='|' read -r t f v e z <<< "$m"
        [ "$t" = "$1" ] && { echo "$f|$v"; return 0; }
    done
    return 1
}

if [ -z "$ONLY" ]; then
    # The cross-model directional tests feed Figure 2d, so they run before it.
    python3 apm_crossmodel.py
    python3 lean_confirm.py --tags RevealLO,REVEAL,GLADM35,SPiRaL,SEMUCB-WM1,RevealLO_30km
    python3 crossmodel_table.py

    IFS='|' read -r PFILE PVAR <<< "$(model_file "$PAPER_MODEL")"
    python3 fig1_map.py       --tag "$PAPER_MODEL" --out "$FIGDIR/fig1_map"
    python3 fig_workflow.py                        --out "$FIGDIR/fig2_workflow"
    python3 fig_corridor.py                        --out "$FIGDIR/fig3_corridor"
    python3 fig_calibration.py                     --out "$FIGDIR/fig8_calibration"
    python3 fig_lean.py                            --out "$FIGDIR/fig4_lean"
    # Figure 5 reads mid_mantle_summary.csv, so the census is rebuilt first; it costs
    # seconds and loads no model.
    python3 mid_mantle_census.py > logs/mid_mantle_census.log
    python3 fig_bands.py                           --out "$FIGDIR/fig6_bands"
    python3 fig_deflection.py                      --out "$FIGDIR/fig7_deflection"

    python3 fig_si_sweeps.py                       --out "$FIGDIR/figS1_sweeps"
    python3 fig_si_profiles.py                     --out "$FIGDIR/figS2_corridor_profiles"
fi

# The supplement atlas: all 49 on the paper model, and the nine best-constrained
# in each of the others, which is what supports the statement that the models put
# conduits in different places.
for m in "${MODELS[@]}"; do
    IFS='|' read -r tag file var every zmax <<< "$m"
    [ -n "$ONLY" ] && [ "$ONLY" != "$tag" ] && continue
    [ -f "out/conduit_paths_all_$tag.json" ] || { echo "skip $tag: no paths"; continue; }
    if [ "$tag" = "$PAPER_MODEL" ]; then
        python3 sections_figure.py --file "$file" --tag "$tag" --var "$var" --all \
                --out "$FIGDIR/fig9_sections"
    else
        python3 sections_figure.py --file "$file" --tag "$tag" --var "$var" --top 9
    fi
done

# Every label, measured against the width the manuscript places these at. The
# check needs pdfplumber and the drawing does not, so a machine without it still
# gets its figures and is told what it did not get. pdfplumber wants a Pillow
# newer than several unrelated packages accept, so it belongs in an environment
# of its own rather than in front of whatever else is installed:
#
#     python3 -m venv .venv-figcheck
#     .venv-figcheck/bin/pip install -q pdfplumber
#
# The paper-model atlas is main text now (Figures 8-11, one run of --all paginated
# 12/12/12/13), and the supplement keeps only the sweeps, the corridor profiles, and
# the other-model sections, S3a to S3c. No filename rule can infer any of this from
# the runs that produced the files, so the mapping is written here, beside the run
# that produced them, and cannot describe figures that were never drawn.
{
  echo "# generated by refigure.sh; figure number then file, one pair per line"
  echo "1  fig1_map.png"
  echo "2  fig2_workflow.png"
  echo "3  fig3_corridor.png"
  echo "4  fig4_lean.png"
  echo "5  fig6_bands.png"
  echo "6  fig7_deflection.png"
  echo "7  fig8_calibration.png"
  echo "8  fig9_sections_p1.png"
  echo "9  fig9_sections_p2.png"
  echo "10 fig9_sections_p3.png"
  echo "11 fig9_sections_p4.png"
  echo "s1 figS1_sweeps.png"
  echo "s2 figS2_corridor_profiles.png"
  echo "s3a fig_wedges_REVEAL_top9.png"
  echo "s3b fig_wedges_GLADM35_top9.png"
  echo "s3c fig_wedges_SEMUCB-WM1_top9.png"
} > "$FIGDIR/figure_map.txt"

PY=python3
[ -x .venv-figcheck/bin/python3 ] && PY=.venv-figcheck/bin/python3
python3 check_figure_map.py

if compgen -G "$FIGDIR/*.pdf" > /dev/null; then
    "$PY" figcheck.py "$FIGDIR"/*.pdf || echo 'figures are written; the check above did not run'
else
    echo 'no figures were written' >&2; exit 1
fi
